### PR TITLE
Lots of fixes and modifications

### PR DESCRIPTION
**Pull request by petehamilton**
Yo,
I decided this was a really cool project and so went to work on the ui a bit. Hopefully you like the changes!
- Cleaned up the backend structure loads removing extra files and boilerplate leftovers.
- Slightly different page layout with a stretched header and more whitespace
- Implemented a better javascript setup with namespaces lists of machines and seperate functions for refreshing the map and list and adding bindings.
- The list is also now the same height as the map and they're both on the same level so it's easier to read.
- Made the map static, actually seems nicer this way as the layout seems more consistent

You can see an example (uses static JSON) at [My DOC site](https://www.doc.ic.ac.uk/~peh10/labmap-web/)

### CODE REVIEW

**Comment by chpatrick** [comment]
Sweet, thanks. I kinda liked zooming though, can you think of some kind of compromise?

**Comment by petehamilton** [comment]
I agree, but I'm trying to think of way which maintains the nice aspect/viewport but let's you zoom in and out. I'm sure we can come up with something

I was thinking maybe if you initiate the handlers once you enter the map viewport and cancel the once you leave that could work?

Something like (pseudo)

svmap.mouseover:
    svgpanzoomer = handler.setup() // svgpanzoomer is now the listener?

svgmap.mouseout:
    svgpanzoomer = null //Now no listeners

I've done it like this for similar things before but never with SVG and I'm not sure how the pan zoom things works. Also if we do bring it back, would be nice to have a reset button as well.

P

**Comment by chpatrick** [comment]
I don't know how difficult this would be to implement but the area currently showing user info could display a magnified version of the map where the cursor is pointing.

**Comment by petehamilton** [comment]
I know that's easy for images, loads of js plugins, not sure how it would work for SVG though.

**Pull request merged**
